name: flutter_sticky_header
description: Flutter implementation of sticky headers as a sliver. Use it in a CustomScrollView.
version: 0.6.4
homepage: https://github.com/letsar/flutter_sticky_header

dependencies:
  flutter:
    sdk: flutter
  value_layout_builder: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sliver_tools: ^0.2.12

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3 <4.0.0"
